import{app,analytics}from './firebase-config.js';import{getStorage}from "firebase/storage";document.addEventListener('DOMContentLoaded',function(){console.log('WebRamp Website Loading...');const storage=getStorage(app);const navToggle=document.getElementById('nav-toggle');const navMenu=document.getElementById('nav-menu');if(navToggle&&navMenu){navToggle.addEventListener('click',function(){navMenu.classList.toggle('active');navToggle.classList.toggle('active')});const navLinks=document.querySelectorAll('.nav-link');navLinks.forEach(link=>{link.addEventListener('click',()=>{navMenu.classList.remove('active');navToggle.classList.remove('active')})})}
const navbar=document.querySelector('.navbar');if(navbar){window.addEventListener('scroll',function(){if(window.scrollY>100){navbar.classList.add('scrolled')}else{navbar.classList.remove('scrolled')}})}
const navLinks=document.querySelectorAll('a[href^="#"]');navLinks.forEach(link=>{link.addEventListener('click',function(e){e.preventDefault();const targetId=this.getAttribute('href');const targetElement=document.querySelector(targetId);if(targetElement){targetElement.scrollIntoView({behavior:'smooth',block:'start'})}})});const serviceCards=document.querySelectorAll('.service-card');serviceCards.forEach(card=>{card.addEventListener('mouseenter',function(){this.style.transform='translateY(-10px)';this.style.transition='all 0.3s ease'});card.addEventListener('mouseleave',function(){this.style.transform='translateY(0)'})});const featureCards=document.querySelectorAll('.feature-card');featureCards.forEach(card=>{card.addEventListener('mouseenter',function(){this.style.transform='translateY(-5px)';this.style.transition='all 0.3s ease'});card.addEventListener('mouseleave',function(){this.style.transform='translateY(0)'})});const serviceItems=document.querySelectorAll('.service-item');serviceItems.forEach(item=>{item.addEventListener('mouseenter',function(){this.style.transform='translateY(-5px)';this.style.transition='all 0.3s ease'});item.addEventListener('mouseleave',function(){this.style.transform='translateY(0)'})});const buttons=document.querySelectorAll('.btn-primary, .btn-secondary, .nav-cta');buttons.forEach(button=>{button.addEventListener('mouseenter',function(){this.style.transform='translateY(-2px)';this.style.transition='all 0.3s ease'});button.addEventListener('mouseleave',function(){this.style.transform='translateY(0)'})});const sections=document.querySelectorAll('section[id]');const navLinksAll=document.querySelectorAll('.nav-link');function highlightNavLink(){let current='';sections.forEach(section=>{const sectionTop=section.offsetTop;const sectionHeight=section.clientHeight;if(window.scrollY>=(sectionTop-200)){current=section.getAttribute('id')}});navLinksAll.forEach(link=>{link.classList.remove('active');if(link.getAttribute('href')===`#${current}`){link.classList.add('active')}})}
window.addEventListener('scroll',highlightNavLink);window.addEventListener('load',function(){document.body.style.opacity='1';document.body.style.transition='opacity 0.5s ease'});document.body.style.opacity='0';const testimonialsScroll=document.querySelector('.testimonials-scroll');if(testimonialsScroll){const testimonials=testimonialsScroll.innerHTML;testimonialsScroll.innerHTML=testimonials+testimonials;testimonialsScroll.addEventListener('mouseenter',function(){this.style.animationPlayState='paused'});testimonialsScroll.addEventListener('mouseleave',function(){this.style.animationPlayState='running'})}
const statItems=document.querySelectorAll('.stat-item');statItems.forEach(item=>{item.addEventListener('mouseenter',function(){this.style.transform='translateY(-5px)';this.style.transition='all 0.3s ease'});item.addEventListener('mouseleave',function(){this.style.transform='translateY(0)'})});const logoItems=document.querySelectorAll('.logo-item');logoItems.forEach(item=>{item.addEventListener('mouseenter',function(){this.style.transform='translateY(-5px)';this.style.transition='all 0.3s ease'});item.addEventListener('mouseleave',function(){this.style.transform='translateY(0)'})});const siteAuditForm=document.getElementById('siteAuditForm');if(siteAuditForm){siteAuditForm.addEventListener('submit',function(e){e.preventDefault();const formData=new FormData(this);const auditData={name:formData.get('name'),email:formData.get('email'),phone:formData.get('phone'),website:formData.get('website'),business:formData.get('business'),goals:formData.get('goals')};const submitButton=this.querySelector('.btn-primary');const originalText=submitButton.textContent;submitButton.textContent='Processing...';submitButton.disabled=!0;setTimeout(()=>{alert('Thank you! Your audit request has been submitted. We\'ll send your detailed report within 24 hours.');this.reset();submitButton.textContent=originalText;submitButton.disabled=!1},2000)})}
const seoAuditForm=document.getElementById('seoAuditForm');if(seoAuditForm){seoAuditForm.addEventListener('submit',function(e){e.preventDefault();const website=this.querySelector('#seoWebsite').value;const email=this.querySelector('#seoEmail').value;const submitButton=this.querySelector('.seo-audit-btn');const originalText=submitButton.textContent;submitButton.textContent='PROCESSING...';submitButton.disabled=!0;setTimeout(()=>{alert('Thank you! Your free SEO audit request has been submitted. We\'ll send your detailed report within 24 hours.');this.reset();submitButton.textContent=originalText;submitButton.disabled=!1},2000)})}
function animateAboutCounters(){const counters=document.querySelectorAll('[data-count]');counters.forEach(counter=>{const target=parseInt(counter.getAttribute('data-count'));const duration=2000;const increment=target/(duration/16);let current=0;const timer=setInterval(()=>{current+=increment;if(current>=target){counter.textContent=target+'+';clearInterval(timer)}else{counter.textContent=Math.floor(current)+'+'}},16)})}
function initScrollAnimations(){const observerOptions={threshold:0.1,rootMargin:'0px 0px -50px 0px'};const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){if(entry.target.classList.contains('about-stats')){animateAboutCounters()}
entry.target.classList.add('animate-in')}})},observerOptions);document.querySelectorAll('.about-stats, .stat-showcase-item, .expertise-category, .process-step').forEach(el=>{observer.observe(el)})}
initScrollAnimations();function initDigitalSuiteAnimations(){const observerOptions={threshold:0.1,rootMargin:'0px 0px -50px 0px'};const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('animate-in');if(entry.target.classList.contains('service-card')){const cards=entry.target.parentElement.querySelectorAll('.service-card');cards.forEach((card,index)=>{setTimeout(()=>{card.classList.add('animate-in')},index*100)})}
if(entry.target.classList.contains('process-step')){const steps=entry.target.parentElement.querySelectorAll('.process-step');steps.forEach((step,index)=>{setTimeout(()=>{step.classList.add('animate-in')},index*150)})}}})},observerOptions);document.querySelectorAll('.service-card, .process-step, .metric-card-large, .certification-card, .strength-item').forEach(el=>{observer.observe(el)})}
function initSmoothScroll(){document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){e.preventDefault();const target=document.querySelector(this.getAttribute('href'));if(target){target.scrollIntoView({behavior:'smooth',block:'start'})}})})}
function initFormValidation(){const forms=document.querySelectorAll('form');forms.forEach(form=>{form.addEventListener('submit',function(e){e.preventDefault();const inputs=form.querySelectorAll('input[required]');let isValid=!0;inputs.forEach(input=>{if(!input.value.trim()){isValid=!1;input.classList.add('error')}else{input.classList.remove('error')}});if(isValid){const submitBtn=form.querySelector('button[type="submit"]');const originalText=submitBtn.textContent;submitBtn.textContent='PROCESSING...';submitBtn.disabled=!0;setTimeout(()=>{alert('Thank you! Your request has been submitted successfully.');submitBtn.textContent=originalText;submitBtn.disabled=!1;form.reset()},2000)}})})}
document.addEventListener('DOMContentLoaded',function(){const seoForm=document.getElementById('seoAuditForm');if(seoForm){seoForm.addEventListener('submit',function(e){e.preventDefault();const website=document.getElementById('seoWebsite').value;const email=document.getElementById('seoEmail').value;if(website&&email){const submitBtn=document.querySelector('.seo-audit-btn');const originalText=submitBtn.textContent;submitBtn.textContent='PROCESSING...';submitBtn.disabled=!0;setTimeout(()=>{alert('Thank you! Your free SEO audit request has been submitted. We\'ll deliver your personalized report within 24 hours.');submitBtn.textContent=originalText;submitBtn.disabled=!1;document.getElementById('seoAuditForm').reset()},2000)}})}
const video=document.getElementById('heroVideo');const videoLoading=document.getElementById('videoLoading');const videoPlayOverlay=document.getElementById('videoPlayOverlay');if(video){console.log('Video element found, initializing...');video.style.display='block';video.style.visibility='visible';video.style.opacity='1';setTimeout(()=>{console.log('Attempting to play video...');video.play().then(()=>{console.log('Video playing successfully');if(videoLoading)videoLoading.style.display='none';if(videoPlayOverlay)videoPlayOverlay.style.display='none'}).catch(e=>{console.log('Autoplay failed, showing play button:',e);if(videoLoading)videoLoading.style.display='none';if(videoPlayOverlay)videoPlayOverlay.style.display='flex'})},2000);video.addEventListener('loadstart',function(){console.log('Video load started');if(videoLoading)videoLoading.style.display='flex'});video.addEventListener('loadeddata',function(){console.log('Video data loaded');if(videoLoading)videoLoading.style.display='none';video.play().catch(e=>{console.log('Play failed after load:',e);if(videoPlayOverlay)videoPlayOverlay.style.display='flex'})});video.addEventListener('canplay',function(){console.log('Video can play');if(videoLoading)videoLoading.style.display='none';video.play().catch(e=>{console.log('Play failed when ready:',e);if(videoPlayOverlay)videoPlayOverlay.style.display='flex'})});video.addEventListener('playing',function(){console.log('Video is now playing');if(videoLoading)videoLoading.style.display='none';if(videoPlayOverlay)videoPlayOverlay.style.display='none'});video.addEventListener('error',function(e){console.error('Video error:',e);if(videoLoading){videoLoading.innerHTML=`
                    <div style="text-align: center;">
                        <i class="fas fa-exclamation-triangle" style="font-size: 2rem; color: #ef4444; margin-bottom: 10px;"></i>
                        <p style="color: #ef4444; margin: 0;">Video failed to load</p>
                        <a href="VIDEO/RAJ series 1.mp4" style="color: #3b82f6; text-decoration: underline; margin-top: 10px; display: inline-block;">Download Video</a>
                    </div>
                `;videoLoading.style.display='flex'}});if(videoPlayOverlay){videoPlayOverlay.addEventListener('click',function(){console.log('Play button clicked');video.play().then(()=>{console.log('Manual play successful');videoPlayOverlay.style.display='none'}).catch(e=>{console.error('Manual play failed:',e)})})}
video.style.background='transparent';video.style.backgroundColor='transparent'}
function initFAQ(){const faqItems=document.querySelectorAll('.faq-item');console.log('Found FAQ items:',faqItems.length);if(faqItems.length===0){console.log('No FAQ items found, retrying...');setTimeout(initFAQ,1000);return}
faqItems.forEach((item,index)=>{const question=item.querySelector('.faq-question');const answer=item.querySelector('.faq-answer');if(question&&answer){console.log(`FAQ item ${index + 1} initialized`);question.removeEventListener('click',handleFAQClick);question.addEventListener('click',(e)=>{e.preventDefault();e.stopPropagation();console.log(`FAQ item ${index + 1} clicked`);const isActive=item.classList.contains('active');faqItems.forEach((otherItem,otherIndex)=>{if(otherItem!==item){otherItem.classList.remove('active');console.log(`FAQ item ${otherIndex + 1} closed`)}});if(isActive){item.classList.remove('active');console.log(`FAQ item ${index + 1} closed`)}else{item.classList.add('active');console.log(`FAQ item ${index + 1} opened`)}})}})}
function handleFAQClick(e){e.preventDefault();e.stopPropagation()}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initFAQ)}else{initFAQ()}
function toggleFAQ(element){const faqItem=element.parentElement;const answer=faqItem.querySelector('.faq-answer');const icon=element.querySelector('i');document.querySelectorAll('.faq-item').forEach(item=>{if(item!==faqItem){const otherAnswer=item.querySelector('.faq-answer');const otherIcon=item.querySelector('i');otherAnswer.style.maxHeight='0';otherAnswer.style.padding='0 20px';otherIcon.style.transform='rotate(0deg)'}});if(answer.style.maxHeight==='0px'||answer.style.maxHeight===''){answer.style.maxHeight='200px';answer.style.padding='0 20px';icon.style.transform='rotate(180deg)'}else{answer.style.maxHeight='0';answer.style.padding='0 20px';icon.style.transform='rotate(0deg)'}}
initDigitalSuiteAnimations();initSmoothScroll();initFormValidation()});function toggleNewFAQ(element){console.log('FAQ toggle function called');const faqItem=element.parentElement;const answer=faqItem.querySelector('.faq-answer-new');const icon=element.querySelector('.faq-icon');console.log('FAQ item:',faqItem);console.log('Answer element:',answer);console.log('Icon element:',icon);document.querySelectorAll('.faq-item-new').forEach(item=>{if(item!==faqItem){item.classList.remove('active');const otherAnswer=item.querySelector('.faq-answer-new');const otherIcon=item.querySelector('.faq-icon');if(otherAnswer){otherAnswer.style.maxHeight='0';otherAnswer.style.padding='0 30px';otherAnswer.style.display='block'}
if(otherIcon){otherIcon.style.transform='rotate(0deg)';otherIcon.style.background='rgba(59, 130, 246, 0.1)';otherIcon.style.color='#3b82f6'}}});if(faqItem.classList.contains('active')){faqItem.classList.remove('active');if(answer){answer.style.maxHeight='0';answer.style.padding='0 30px';answer.style.display='block'}
if(icon){icon.style.transform='rotate(0deg)';icon.style.background='rgba(59, 130, 246, 0.1)';icon.style.color='#3b82f6'}}else{faqItem.classList.add('active');if(answer){answer.style.maxHeight='300px';answer.style.padding='25px 30px';answer.style.display='block';answer.style.visibility='visible';answer.style.opacity='1'}
if(icon){icon.style.transform='rotate(45deg)';icon.style.background='#3b82f6';icon.style.color='white'}}
console.log('FAQ toggle completed')}
console.log('WebRamp Website Loaded Successfully! 🚀')})